n = input('Digite um valor: ')
print('Valor digitado: {}'.format(n))
print('Número: {}'.format(n.isalnum()))
print('Alfanumérico: {}'.format(n.isalnum()))
print('Alfabético: {}'.format(n.isalpha()))
print('Numérico: {}'.format(n.isnumeric()))
print('Decimal: {}'.format(n.isdecimal()))
print('Dígito: {}'.format(n.isdigit()))
print('Identificador: {}'.format(n.isidentifier()))
print('Minuscula: {}'.format(n.islower()))
print('Printável: {}'.format(n.isprintable()))
print('Espaço: {}'.format(n.isspace()))
print('Título: {}'.format(n.istitle()))
print('Maiúscula: {}'.format(n.isupper()))
